// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths {
    public static var grid: Grid {
        Grid(path: "/grid")
    }

    public struct Grid {
        /// Path: `/grid`
        public let path: String
    }
}
