// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.Timeseries.Historical.WithResourceID {
    public var metadata: Metadata {
        Metadata(path: path + "/metadata")
    }

    public struct Metadata {
        /// Path: `/timeseries/historical/{resource_id}/metadata`
        public let path: String

        /// Historical Timeseries Metadata
        public var get: Request<geosphereAustriaAPIKit.GridHistoricalMetadataModel> {
            Request(path: path, method: "GET", id: "Historical_Timeseries_Metadata_timeseries_historical__resource_id__metadata_get")
        }
    }
}
