// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.Station {
    public var current: Current {
        Current(path: path + "/current")
    }

    public struct Current {
        /// Path: `/station/current`
        public let path: String
    }
}
