// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.Grid {
    public var forecast: Forecast {
        Forecast(path: path + "/forecast")
    }

    public struct Forecast {
        /// Path: `/grid/forecast`
        public let path: String
    }
}
