// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.Station {
    public func mode(_ mode: String) -> WithMode {
        WithMode(path: "\(path)/\(mode)")
    }

    public struct WithMode {
        /// Path: `/station/{mode}`
        public let path: String
    }
}
