// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.Station.Historical.WithResourceID {
    public var metadata: Metadata {
        Metadata(path: path + "/metadata")
    }

    public struct Metadata {
        /// Path: `/station/historical/{resource_id}/metadata`
        public let path: String

        /// Historical Station Metadata
        public var get: Request<geosphereAustriaAPIKit.StationHistoricalMetadataModel> {
            Request(path: path, method: "GET", id: "Historical_Station_Metadata_station_historical__resource_id__metadata_get")
        }
    }
}
