// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.Grid.Historical.WithResourceID {
    public var metadata: Metadata {
        Metadata(path: path + "/metadata")
    }

    public struct Metadata {
        /// Path: `/grid/historical/{resource_id}/metadata`
        public let path: String

        /// Historical Grid Metadata
        public var get: Request<geosphereAustriaAPIKit.GridHistoricalMetadataModel> {
            Request(path: path, method: "GET", id: "Historical_Grid_Metadata_grid_historical__resource_id__metadata_get")
        }
    }
}
