// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths {
    public static var datasets: Datasets {
        Datasets(path: "/datasets")
    }

    public struct Datasets {
        /// Path: `/datasets`
        public let path: String

        /// View And Filter All Available Datasets
        public func get(type: `Type`? = nil, mode: Mode? = nil) -> Request<[String: geosphereAustriaAPIKit.Dataset]> {
            Request(path: path, method: "GET", query: makeGetQuery(type, mode), id: "View_and_filter_all_available_datasets_datasets_get")
        }

        private func makeGetQuery(_ type: `Type`?, _ mode: Mode?) -> [(String, String?)] {
            let encoder = URLQueryEncoder()
            encoder.encode(type, forKey: "type")
            encoder.encode(mode, forKey: "mode")
            return encoder.items
        }

        /// EndpointType
        ///
        /// An enumeration.
        public enum `Type`: String, Codable, CaseIterable {
            case grid
            case timeseries
            case station
        }

        /// EndpointMode
        ///
        /// An enumeration.
        public enum Mode: String, Codable, CaseIterable {
            case historical
            case current
            case forecast
        }
    }
}
