// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.Grid.Forecast.WithResourceID {
    public var metadata: Metadata {
        Metadata(path: path + "/metadata")
    }

    public struct Metadata {
        /// Path: `/grid/forecast/{resource_id}/metadata`
        public let path: String

        /// Grid Forecast Metadata
        public var get: Request<geosphereAustriaAPIKit.GridForecastMetadataModel> {
            Request(path: path, method: "GET", id: "Grid_Forecast_Metadata_grid_forecast__resource_id__metadata_get")
        }
    }
}
