// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.Grid.Historical.WithResourceID.Metadata {
    public var parameters: Parameters {
        Parameters(path: path + "/parameters")
    }

    public struct Parameters {
        /// Path: `/grid/historical/{resource_id}/metadata/parameters`
        public let path: String

        /// Historical Grid Parameter Metadata Csv
        public func get(filename: String? = nil) -> Request<AnyJSON> {
            Request(path: path, method: "GET", query: makeGetQuery(filename), id: "Historical_Grid_Parameter_Metadata_CSV_grid_historical__resource_id__metadata_parameters_get")
        }

        private func makeGetQuery(_ filename: String?) -> [(String, String?)] {
            let encoder = URLQueryEncoder()
            encoder.encode(filename, forKey: "filename")
            return encoder.items
        }
    }
}
