// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.Station.WithMode {
    public func resourceID(_ resourceID: String) -> WithResourceID {
        WithResourceID(path: "\(path)/\(resourceID)")
    }

    public struct WithResourceID {
        /// Path: `/station/{mode}/{resource_id}`
        public let path: String
    }
}
