// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths {
    public static var timeseries: Timeseries {
        Timeseries(path: "/timeseries")
    }

    public struct Timeseries {
        /// Path: `/timeseries`
        public let path: String
    }
}
