// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.Station.Historical.WithResourceID.Metadata {
    public func mdtype(_ mdtype: String) -> WithMdtype {
        WithMdtype(path: "\(path)/\(mdtype)")
    }

    public struct WithMdtype {
        /// Path: `/station/historical/{resource_id}/metadata/{mdtype}`
        public let path: String

        /// Historical Station Metadata Csv
        public func get(filename: String? = nil) -> Request<AnyJSON> {
            Request(path: path, method: "GET", query: makeGetQuery(filename), id: "Historical_Station_Metadata_CSV_station_historical__resource_id__metadata__mdtype__get")
        }

        private func makeGetQuery(_ filename: String?) -> [(String, String?)] {
            let encoder = URLQueryEncoder()
            encoder.encode(filename, forKey: "filename")
            return encoder.items
        }
    }
}
