// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.Timeseries.Forecast.WithResourceID {
    public var metadata: Metadata {
        Metadata(path: path + "/metadata")
    }

    public struct Metadata {
        /// Path: `/timeseries/forecast/{resource_id}/metadata`
        public let path: String

        /// Timeseries Forecast Metadata
        public var get: Request<geosphereAustriaAPIKit.GridForecastMetadataModel> {
            Request(path: path, method: "GET", id: "Timeseries_Forecast_Metadata_timeseries_forecast__resource_id__metadata_get")
        }
    }
}
