// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.Grid {
    public var historical: Historical {
        Historical(path: path + "/historical")
    }

    public struct Historical {
        /// Path: `/grid/historical`
        public let path: String
    }
}
