// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths {
    public static var station: Station {
        Station(path: "/station")
    }

    public struct Station {
        /// Path: `/station`
        public let path: String
    }
}
