// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

/// An enumeration.
public enum Bundesland: String, Codable, CaseIterable {
    case burgenland = "Burgenland"
    case kärnten = "Kärnten"
    case niederösterreich = "Niederösterreich"
    case oberösterreich = "Oberösterreich"
    case salzburg = "Salzburg"
    case steiermark = "Steiermark"
    case tirol = "Tirol"
    case vorarlberg = "Vorarlberg"
    case wien = "Wien"
}
