// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

/// An enumeration.
public enum EndpointMode: String, Codable, CaseIterable {
    case historical
    case current
    case forecast
}
