// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

/// An enumeration.
public enum EndpointType: String, Codable, CaseIterable {
    case grid
    case timeseries
    case station
}
