// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct GeoJSONFeatureParameter: Codable {
    /// Example: "RR"
    public var name: String
    /// Example: "kg m-2"
    public var unit: String
    /// Example:
    ///
    /// [
    ///   9,
    ///   0
    /// ]
    //public var data: [Double]
    public var data: [Double?] // Allow null values with `Optional`

    public init(name: String, unit: String, data: [Double]) {
        self.name = name
        self.unit = unit
        self.data = data
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.name = try values.decode(String.self, forKey: "name")
        self.unit = try values.decode(String.self, forKey: "unit")
        //self.data = try values.decode([Double].self, forKey: "data")
        self.data = try values.decodeIfPresent([Double?].self, forKey: "data") ?? []
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(name, forKey: "name")
        try values.encode(unit, forKey: "unit")
        try values.encode(data, forKey: "data")
    }
}
