// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct GeoJSONPoint: Codable {
    /// Example: "Point"
    public var type: String?
    /// Point coordinates are in x, y order (easting, northing for projected coordinates, longitude, and latitude for geographic coordinates)
    ///
    /// Example:
    ///
    /// [
    ///   16.356388092041016,
    ///   48.248611450195312
    /// ]
    public var coordinates: [Double]

    public init(type: String? = nil, coordinates: [Double]) {
        self.type = type
        self.coordinates = coordinates
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.type = try values.decodeIfPresent(String.self, forKey: "type")
        self.coordinates = try values.decode([Double].self, forKey: "coordinates")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(type, forKey: "type")
        try values.encode(coordinates, forKey: "coordinates")
    }
}
