// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct GeoJSONFeatureProperties: Codable {
    public var parameters: [String: GeoJSONFeatureParameter]

    public init(parameters: [String: GeoJSONFeatureParameter]) {
        self.parameters = parameters
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.parameters = try values.decode([String: GeoJSONFeatureParameter].self, forKey: "parameters")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(parameters, forKey: "parameters")
    }
}
