// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

/// An enumeration.
public enum IDType: String, Codable, CaseIterable {
    case synop = "Synop"
    case klima = "Klima"
}
