// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

/// An enumeration.
public enum MDType: String, Codable, CaseIterable {
    case stations
    case parameters
}
