// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

/// An enumeration.
public enum OutputFormat: String, Codable, CaseIterable {
    case geojson
    case netcdf
    case csv
}
