// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct ParameterMetadataModel: Codable {
    /// Example: "RR"
    public var name: String
    /// Example: "1-hour precipitation sum"
    public var longName: String
    /// Example: "1-hour precipitation sum"
    public var desc: String
    /// Example: "kg m-2"
    public var unit: String

    public init(name: String, longName: String, desc: String, unit: String) {
        self.name = name
        self.longName = longName
        self.desc = desc
        self.unit = unit
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.name = try values.decode(String.self, forKey: "name")
        self.longName = try values.decode(String.self, forKey: "long_name")
        self.desc = try values.decode(String.self, forKey: "desc")
        self.unit = try values.decode(String.self, forKey: "unit")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(name, forKey: "name")
        try values.encode(longName, forKey: "long_name")
        try values.encode(desc, forKey: "desc")
        try values.encode(unit, forKey: "unit")
    }
}
