// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct StationGeoJSONFeature: Codable {
    /// Example: "Feature"
    public var type: String?
    /// GeoJSONPoint
    public var geometry: GeoJSONPoint
    /// StationGeoJSONProperties
    public var properties: StationGeoJSONProperties

    public init(type: String? = nil, geometry: GeoJSONPoint, properties: StationGeoJSONProperties) {
        self.type = type
        self.geometry = geometry
        self.properties = properties
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.type = try values.decodeIfPresent(String.self, forKey: "type")
        self.geometry = try values.decode(GeoJSONPoint.self, forKey: "geometry")
        self.properties = try values.decode(StationGeoJSONProperties.self, forKey: "properties")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(type, forKey: "type")
        try values.encode(geometry, forKey: "geometry")
        try values.encode(properties, forKey: "properties")
    }
}
