// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct StationGeoJSONProperties: Codable {
    public var parameters: [String: GeoJSONFeatureParameter]
    public var station: String

    public init(parameters: [String: GeoJSONFeatureParameter], station: String) {
        self.parameters = parameters
        self.station = station
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.parameters = try values.decode([String: GeoJSONFeatureParameter].self, forKey: "parameters")
        self.station = try values.decode(String.self, forKey: "station")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(parameters, forKey: "parameters")
        try values.encode(station, forKey: "station")
    }
}
