// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

/// An enumeration.
public enum StationMetadataType: String, Codable, CaseIterable {
    case combined = "COMBINED"
    case subStation = "SUB_STATION"
    case individual = "INDIVIDUAL"
}
