// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct StationFilterResponseDto: Codable {
    public var numStationsTotal: Int
    public var numStationsMatching: Int
    public var matchingStations: [StationMetadataDto]

    public init(numStationsTotal: Int, numStationsMatching: Int, matchingStations: [StationMetadataDto]) {
        self.numStationsTotal = numStationsTotal
        self.numStationsMatching = numStationsMatching
        self.matchingStations = matchingStations
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.numStationsTotal = try values.decode(Int.self, forKey: "num_stations_total")
        self.numStationsMatching = try values.decode(Int.self, forKey: "num_stations_matching")
        self.matchingStations = try values.decode([StationMetadataDto].self, forKey: "matching_stations")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(numStationsTotal, forKey: "num_stations_total")
        try values.encode(numStationsMatching, forKey: "num_stations_matching")
        try values.encode(matchingStations, forKey: "matching_stations")
    }
}
