// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct ValidationError: Codable {
    /// Location
    public var loc: [LocItem]
    /// Message
    public var msg: String
    /// Error Type
    public var type: String

    public struct LocItem: Codable {
        public var string: String?
        public var int: Int?

        public init(string: String? = nil, int: Int? = nil) {
            self.string = string
            self.int = int
        }

        public init(from decoder: Decoder) throws {
            let container = try decoder.singleValueContainer()
            self.string = try? container.decode(String.self)
            self.int = try? container.decode(Int.self)
        }

        public func encode(to encoder: Encoder) throws {
            var container = encoder.singleValueContainer()
            if let value = string { try container.encode(value) }
            if let value = int { try container.encode(value) }
        }
    }

    public init(loc: [LocItem], msg: String, type: String) {
        self.loc = loc
        self.msg = msg
        self.type = type
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.loc = try values.decode([LocItem].self, forKey: "loc")
        self.msg = try values.decode(String.self, forKey: "msg")
        self.type = try values.decode(String.self, forKey: "type")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(loc, forKey: "loc")
        try values.encode(msg, forKey: "msg")
        try values.encode(type, forKey: "type")
    }
}
